Repository googleapis/nodejs-billing-budgets, pull requests merged in 2020-07, with the labels that each got.

#136 build: use bazel build
  src/v1beta1/budget_service_client.ts
  synth.metadata
  synth.py
  test/gapic_budget_service_v1beta1.ts
Labels: automerge, cla: yes

#137 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#138 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#140 feat: added monitoring_notification_channels field to configure additional budget recipients
  protos/google/cloud/billing/budgets/v1beta1/budget_model.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: full

#142 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#143 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#144 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#148 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#147 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#149 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#150 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#151 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#152 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#153 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#154 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
