Repository googleapis/nodejs-billing-budgets, pull requests merged in 2020-05, with the labels that each got.

#122 fix: regen protos and tests
  protos/protos.js
  synth.metadata
  test/gapic_budget_service_v1beta1.ts
Labels: automerge, cla: yes

#123 chore: update linting rules
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#124 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#125 feat: updates Cloud Billing Budget API v1beta1
  protos/google/cloud/billing/budgets/v1beta1/budget_model.proto
  protos/google/cloud/billing/budgets/v1beta1/budget_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1beta1/budget_service_client.ts
  synth.metadata
Labels: cla: yes, context: full
