Repository googleapis/nodejs-billing-budgets, pull requests merged in 2020-11, with the labels that each got.

#178 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#181 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/budget_service_client.ts
  src/v1beta1/budget_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudbilling, automerge, cla: yes

#183 chore: updates to credit_type comments
  protos/google/cloud/billing/budgets/v1beta1/budget_model.proto
  synth.metadata
Labels: api: cloudbilling, cla: yes, context: none

#187 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/budget_service_client.ts
  src/v1beta1/budget_service_client.ts
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: partial

#189 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full
